apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
spec:
  replicas: 1
  template:
    apiService:
      metadata:
        labels:
          failover: enabled
  bootstrapServers: openshift-kafka-bootstrap-kafka-cluster.apps.gke-nmocpt2-us-west1-0.nmocpt2-upic-0.gcp.sandbox.tetrate.io:443
  tls:
    trustedCertificates:
    - secretName: openshift-cluster-ca-cert
      certificate: ca.crt
  http:
    port: 8080