apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
spec:
  replicas: 1
  bootstrapServers: openshift-kafka-bootstrap-kafka.apps.cluster-lbc9w.lbc9w.sandbox2982.opentlc.com:443
  tls:
    trustedCertificates:
    - secretName: openshift-cluster-ca-cert
      certificate: ca.crt
  http:
    port: 8080