apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-kafka-cluster
spec:
  secretName: openshift-kafka-cluster
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  subject:
    organizations:
      - redhat
  dnsNames:
    - openshift-kafka-bootstrap-kafka.apps.gke-nmocpt2-us-west1-0.nmocpt2-upic-0.gcp.sandbox.tetrate.io
    - openshift-kafka-0-kafka.apps.gke-nmocpt2-us-west1-0.nmocpt2-upic-0.gcp.sandbox.tetrate.io
    - openshift-kafka-1-kafka.apps.gke-nmocpt2-us-west1-0.nmocpt2-upic-0.gcp.sandbox.tetrate.io
    - openshift-kafka-2-kafka.apps.gke-nmocpt2-us-west1-0.nmocpt2-upic-0.gcp.sandbox.tetrate.io