apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  template:
    metadata:
      labels:
        app: trafficgenerator
    spec:
      containers:
        - name: trafficgenerator
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              while :; do
                curl -v -k -X POST "http://tier1-gw.tier1-gateway.svc.cluster.local/consumers/bridge-quickstart-consumer-group/instances/consumer2/records" -H 'content-type: application/vnd.kafka.json.v2+json'
                sleep 30
              done
