apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  template:
    metadata:
      labels:
        app: trafficgenerator
    spec:
      containers:
        - name: trafficgenerator
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              while :; do
                curl http://kafka.tetrate.work/consumers/bridge-quickstart-consumer-group/instances/consumer1/records --resolve "kafka.tetrate.work:80:34.135.167.227" -H 'content-type: application/vnd.kafka.json.v2+json' -v
                sleep 10
              done
