apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgenerator
  labels:
    app: trafficgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  template:
    metadata:
      labels:
        app: trafficgenerator
    spec:
      containers:
        - name: trafficgenerator
          image: appropriate/curl
          args:
            - /bin/sh
            - -c
            - |
              RANDOM=$$
              while :; do
                curl http://kafka.tetrate.work/topics/bridge-quickstart-topic --resolve "kafka.tetrate.work:80:34.135.167.227" -H 'content-type: application/vnd.kafka.json.v2+json' -d '{"records": [{"key": "$RANDOM", "value": "sales-lead-0001"}, {"value": "sales-lead-0002"}, {"value": "sales-lead-0003"}]}' -v
                sleep 10
              done
