---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: east-kafka-bridge-ig-config
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: kafka
    tsb.tetrate.io/workspace: kafka-bridges
    tsb.tetrate.io/gatewayGroup: kafka-bridges-gwg
spec:
  displayName: kafka-bridge-ig-config
  workloadSelector:
    namespace: kafka-bridge
    labels:
      app: east-kafka-bridge-ig
  http:
    - hostname: kafka.tetrate.work
      name: east-kafka-tetrate-work
      port: 80
      routing:
        rules:
        - route:
            host: "kafka-bridge/kafka-bridge-bridge-service.kafka-bridge.svc.cluster.local"
            port: 8282